### ISSUE TITLE
error when scalar covariates NULL

### ISSUE THREAD

**Issue by bernard-liew** [b-thi/FuncNN#1]
HI,

I was hoping you could help me troubleshoot this issue. If I want to predict a scalar outcome using purely functional covariates, I seem to hit a road bump.

`library(FuncNN)

tecator = FuncNN::tecator

tecator_resp = as.factor(ifelse(tecator$y$Fat > 25, 1, 0))
tecator_scalar = data.frame(water = tecator$y$Water)

ind = sample(1:length(tecator_resp), round(0.75*length(tecator_resp)))
train_x = tecator$absorp.fdata$data[ind,]
test_x = tecator$absorp.fdata$data[-ind,]
scalar_train = data.frame(tecator_scalar[ind,1])
scalar_test = data.frame(tecator_scalar[-ind,1])
train_y = tecator_resp[ind]
test_y = tecator_resp[-ind]

func_covs_train = list(train_x)
func_covs_test = list

scalar_train2 = data.frame(interc = rep (1, length (train_y)))

fit_class = fnn.fit(resp = train_y,
                    func_cov = func_covs_train,
                    scalar_cov = NULL, 
                    hidden_layers = 6,
                    neurons_per_layer = c(24, 24, 24, 24, 24, 58),
                    activations_in_layers = c("relu", "relu", "relu", "relu", "relu", "linear"),
                    domain_range = list(c(850, 1050)),
                    learn_rate = 0.001,
                    epochs = 100,
                    raw_data = T,
                    early_stopping = T)`

**This gives the error below**

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'print': arguments imply differing number of rows: 100, 140, 400

I tried not removing `scalar_cov = NULL`, even putting a constant intercept as an argument, but the same error arises. My question is, must scalar covariates be present.

Much appreciated for the help.

Regards,
Bernard

**Comment by b-thi** [comment]
Hi Bernard,

Are you using a different data set? The code you sent runs fine for me. You
can download the latest version from CRAN and see if that helps?

I've attached a screenshot of my output for you to see. If you want, you
can send me the exact code you're running and I'll take a look.

If you're looking for a hint, I would say, looking at that error, you
should go back and see how you are splitting your test and train set. And
no, scalar covariates do not need to be present.

Barinder

[image: image.png]

**Comment by bernard-liew** [comment]
HI Barinder,

Many thanks for the reply. The code indeed produced error which I can replicate on my work computer, but not on my laptop. I managed to rectify it, by reinstalling keras & TF, on my work computer. Many thanks again.

Regards,
Bernard

**Comment by yangchino1** [comment]
Does this package depend on specific version of tensorflow or keras? I can run through all examples by running `example(fnn.fit)` without any error when working with tensorflow 1.14, but will get error messages as given above for almost all examples when working with tensorflow 2. I use conda environment.

**Comment by b-thi** [comment]
Hi, yes this package was built on top of a specific version of tensorflow; a future update will result in an update to TF2
